### ISSUE TITLE
http_cache marked as optional dependency

### ISSUE THREAD

**Issue by LostKobrakai** [tanguilp/plug_http_cache#2]
http_cache is marked as an optional dependency, but isn't actually optional.

**Comment by tanguilp** [comment]
This is because I'm working on a pro (paid) version of `http_cache` with some advanced features. To use this pro version with `plug_http_cache`, `http_cache` needs to be marked as optional so that it can be replaced with `http_cache_pro` in the future. Unless there is a better solution but I couldn't think of one.

**Comment by LostKobrakai** [comment]
How about making it optional once it actually is an optional dependency? This is pre 1.0, so you can make that change at any time anyways.

**Comment by tanguilp** [comment]
I'm nearing completion of this project actually. I changed it to optional dep not long ago.

Does it cause any issue in particular?

**Comment by LostKobrakai** [comment]
Not really. I was just looking at the codebase and saw that there's nothing in there making this actually optional.

**Comment by tanguilp** [comment]
Indeed, for now :) Thanks for feedback, and fell free to open new issues if you have other questions or remarks.
